### ISSUE TITLE
Plan Data Storage/Tables

### ISSUE THREAD

**Issue by mjbernet3** [mjbernet3/projectFomo#13]
## What/Why?

As a developer, I want to plan the storage of data, so that I ensure data is stored efficiently and storage does not have to be frequently updated later.

## Tasks

- [x] Research popular event APIs to gain insight on values to store
- [x] Identify database collections
- [x] Determine document structure for each collection
