### ISSUE TITLE
Create collections and security rules

### ISSUE THREAD

**Issue by mjbernet3** [mjbernet3/projectFomo#40]
## What/Why?

As a developer I want to create efficient and secure collections so that data is managed effectively.

## Tasks

- [x] Create userdata collection
- [x] Create event collection
- [x] Add security rules to protect database
