### ISSUE TITLE
Event Clicked UI

### ISSUE THREAD

**Issue by echadwick6** [mjbernet3/projectFomo#43]
## What/Why?

As a user, I want to view an event page, so that I may view more details on the event.

## Tasks

- [x] Create widget for the top half of the page
- [x] Create widget for the external links portion
- [x] Create widget for the second half of the page
- [x] Create full page using a combination of all the widgets
