### ISSUE TITLE
Profile Page UI

### ISSUE THREAD

**Issue by mjbernet3** [mjbernet3/projectFomo#49]
## What/Why?

As a user I want to have a profile page so that I can customize my account and manage my settings.

## Tasks

- [ ] Finalize figma design
- [ ] Create horizontal friends list widget
- [ ] Create profile page UI
