### ISSUE TITLE
Login/Register Forms

### ISSUE THREAD

**Issue by mjbernet3** [mjbernet3/projectFomo#53]
## What/Why?

As a user I want to register and login so that I can use the application.

## Tasks

- [ ] Finish Login Form
- [ ] Create register form
- [ ] Update Login and register pages so that corresponding forms are used in place of existing text fields and submit button
