### ISSUE TITLE
Add data to discover

### ISSUE THREAD

**Issue by mjbernet3** [mjbernet3/projectFomo#61]
## What/Why?

As a user I want to view categorized events so that I can find events I may be interested in.

## Tasks
IMPORTANT: Make sure discover bloc is disposed when user logs out or closes the application so no memory leaks

- [ ] Update event service as needed to get events
- [ ] Create discover bloc to stream events into discover page
- [ ] Refactor discover page to use real data
