### ISSUE TITLE
Polish Pages

### ISSUE THREAD

**Issue by mjbernet3** [mjbernet3/projectFomo#64]
## What/Why?

As a developer I want pages to look good so that users are more inclined to continue to use the app.

## Tasks

- [ ] Finish Discover Page
- [ ] Finish View All Page
- [ ] Finish Event Clicked Page
- [ ] Finish Profile Page
